# Generated by Django 4.1 on 2024-06-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user',
        ),
    ]
