# Generated by Django 4.1 on 2024-06-18 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0010_rename_name_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unlikes',
            field=models.ManyToManyField(related_name='blog_posts_u', to=settings.AUTH_USER_MODEL),
        ),
    ]
